// <auto-generated />
namespace BookeNeest.Data.DB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class TagCategories : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TagCategories));
        
        string IMigrationMetadata.Id
        {
            get { return "201809051249474_TagCategories"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
